function parameterSweepCombinations = importparamsweep(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PARAMETERSWEEPCOMBINATIONS = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  PARAMETERSWEEPCOMBINATIONS = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  parameterSweepCombinations = importfile("/Users/leanneiannucci/Desktop/IQUV_PolMC_Birefringence/parameter sweep/parameterSweepCombinations.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Nov-2022 19:18:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["rad", "mus", "mua", "biref", "thick", "polar"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
parameterSweepCombinations = readtable(filename, opts);

end