function [R_I, R_Q, R_U, R_V, R_AVGDoLP, R_STDAoP, T_I, T_Q, T_U, T_V, T_AVGDoLP, T_STDAoP] = importStokesOut(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [R_I, R_Q, R_U, R_V, R_AVGDOLP, R_STDAOP, T_I, T_Q, T_U, T_V,
%  T_AVGDOLP, T_STDAOP] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [R_I, R_Q, R_U, R_V, R_AVGDOLP, R_STDAOP, T_I, T_Q, T_U, T_V,
%  T_AVGDOLP, T_STDAOP] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [R_I, R_Q, R_U, R_V, R_AVGDoLP, R_STDAoP, T_I, T_Q, T_U, T_V, T_AVGDoLP, T_STDAoP] = importfile("/Users/leanneiannucci/Desktop/IQUV_PolMC_Birefringence/parameter sweep/678-output-Stokes-summary.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Nov-2022 22:31:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["R_I", "R_Q", "R_U", "R_V", "R_AVGDoLP", "R_STDAoP", "T_I", "T_Q", "T_U", "T_V", "T_AVGDoLP", "T_STDAoP"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
R_I = tbl.R_I;
R_Q = tbl.R_Q;
R_U = tbl.R_U;
R_V = tbl.R_V;
R_AVGDoLP = tbl.R_AVGDoLP;
R_STDAoP = tbl.R_STDAoP;
T_I = tbl.T_I;
T_Q = tbl.T_Q;
T_U = tbl.T_U;
T_V = tbl.T_V;
T_AVGDoLP = tbl.T_AVGDoLP;
T_STDAoP = tbl.T_STDAoP;
end